import Navigation from "./components/Navigation";

export const metadata = {
  title: "The Wild Oasis",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        <main>{children}</main>
        <footer className="">Copyright &copy; by The Wild Oasis</footer>
      </body>
    </html>
  );
}
